### ISSUE TITLE
Bridge Token Total Circulating Issue

### ISSUE THREAD

**Issue by tlatkdgus1** [DefiLlama/peggedassets-server#373]
Thank you for adding BTCUSD.

A minor issue, the Total Circulating for btcusd bridged to Base doesn't seem to be displaying correctly.

I would like to fix this myself, but I don't know how.
[bitcoin-usd-btcfi](https://github.com/DefiLlama/peggedassets-server/blob/94eecee9c900f9a44002b4488b99aba2c824e98f/src/adapters/peggedAssets/bitcoin-usd-btcfi/index.ts#L5)
[defillama](https://defillama.com/stablecoin/bitcoin-usd)

To display correctly, need to exclude the amount locked in the bifrost network [Vault contract](https://explorer.mainnet.bifrostnetwork.com/address/0xD85EB87caB9041ad00764b95796702b1104F42D7) from the bifrost network and check the totalSupply of the base network.

**Comment by Define101** [comment]
@tlatkdgus1 please hard refresh the page
https://defillama.com/stablecoin/bitcoin-usd
![image](https://github.com/user-attachments/assets/a2f54255-ce23-42fd-aa05-8043df57bf6d)

**Comment by tlatkdgus1** [comment]
> @tlatkdgus1 please hard refresh the page https://defillama.com/stablecoin/bitcoin-usd ![image](https://private-user-images.githubusercontent.com/93603962/357335052-a2f54255-ce23-42fd-aa05-8043df57bf6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzg0MjksIm5iZiI6MTcyMzUzODEyOSwicGF0aCI6Ii85MzYwMzk2Mi8zNTczMzUwNTItYTJmNTQyNTUtY2UyMy00MmZkLWFhMDUtODA0M2RmNTdiZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxODBmYThkNjIxMzMxODE1ODNjNTliZmRjM2FiY2JjMGYzNTE5ODg4N2YzNGU0Y2IwNDk5NTdlNDkwMmJmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DABvEno1hYqSidKJ0ABPIR2IHimUWdwBPyf6kDOERy8)

Thank you 👍  I've checked, it seems to be displaying fine.
